// Generated by CoffeeScript 1.10.0
var numPages, state;

numPages = 4;

state = -1;

numPages++;

setInterval(function() {
  state++;
  document.getElementById('mainIndexNumber').style.display = 'none';
  document.getElementById('indexWithBar').style.display = 'none';
  document.getElementById('splashImage').style.display = 'none';
  document.getElementById('breakdown').style.display = 'none';
  document.getElementById('breakdownDetail').style.display = 'none';
  if (state % numPages === 0) {
    return document.getElementById('splashImage').style.display = 'block';
  } else if (state % numPages === 1) {
    return document.getElementById('mainIndexNumber').style.display = 'block';
  } else if (state % numPages === 2) {
    return document.getElementById('indexWithBar').style.display = 'block';
  } else if (state % numPages === 3) {
    return document.getElementById('breakdown').style.display = 'block';
  } else if (state % numPages === 4) {
    return document.getElementById('breakdownDetail').style.display = 'block';
  }
}, 2000);

//# sourceMappingURL=main.js.map
