// Generated by CoffeeScript 1.10.0
var ANIM_STATE_IN, ANIM_STATE_NONE, ANIM_STATE_OUT, STATE_LOADING, STATE_SHOWING_PAGE, animState, loadRaptureIndexData, numPages, state;

STATE_LOADING = 0;

STATE_SHOWING_PAGE = 1;

ANIM_STATE_IN = 0;

ANIM_STATE_NONE = 1;

ANIM_STATE_OUT = 2;

numPages = 4;

$('#animator').on('mouseover', function() {
  return $('.perspectiveAnimatable').addClass('leftRotate').removeClass('rightRotate');
});

$('#animator').on('mouseout', function() {});

state = -1;

animState = ANIM_STATE_IN;

numPages++;

setInterval(function() {
  var switchDivs;
  switchDivs = function() {
    console.log(state + " " + state % numPages);
    document.getElementById('mainIndexNumber').style.display = 'none';
    document.getElementById('indexWithBar').style.display = 'none';
    document.getElementById('splashImage').style.display = 'none';
    document.getElementById('breakdown').style.display = 'none';
    document.getElementById('breakdownDetail').style.display = 'none';
    if (state % numPages === 0) {
      document.getElementById('splashImage').style.display = 'block';
    } else if (state % numPages === 1) {
      document.getElementById('mainIndexNumber').style.display = 'block';
    } else if (state % numPages === 2) {
      document.getElementById('indexWithBar').style.display = 'block';
    } else if (state % numPages === 3) {
      document.getElementById('breakdown').style.display = 'block';
    } else if (state % numPages === 4) {
      document.getElementById('breakdownDetail').style.display = 'block';
    }
    return setTimeout(function() {
      return $('.perspectiveAnimatable').addClass('rightRotate').removeClass('leftRotate', 1);
    });
  };
  state++;
  $('.perspectiveAnimatable').addClass('leftRotate').removeClass('rightRotate');
  return setTimeout(switchDivs, 800);
}, 2000);

loadRaptureIndexData = function(APIendpointURL) {
  var xmlhttp;
  xmlhttp = void 0;
  if (window.XMLHttpRequest) {
    xmlhttp = new XMLHttpRequest;
  } else {
    xmlhttp = new ActiveXObject('Microsoft.XMLHTTP');
  }
  xmlhttp.onreadystatechange = function() {
    if (xmlhttp.readyState === XMLHttpRequest.DONE) {
      if (xmlhttp.status === 200) {
        console.log(xmlhttp.responseText);
      } else if (xmlhttp.status === 400) {
        alert('There was an error 400');
      } else {
        alert('something else other than 200 was returned');
      }
    }
  };
  xmlhttp.open('GET', APIendpointURL, true);
  xmlhttp.send();
};

loadRaptureIndexData('https://rapture-index-cors-api.appspot.com/');

//# sourceMappingURL=main.js.map
